spring.application.name=todo-task-api
spring.datasource.url=${TODO_DB_URL}
spring.datasource.username=${TODO_DB_USER}
spring.datasource.password=${TODO_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}
